apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "azure-devops-exporter.fullname" . }}
  labels:
    {{- include "azure-devops-exporter.labels" . | nindent 4 }}
data:
  AZURE_DEVOPS_ORGANIZATION: {{ .Values.azureDevOps.organization | quote }}
  AZURE_DEVOPS_PROJECTS: {{ .Values.azureDevOps.projects | quote }}
  AZURE_DEVOPS_API_URL: {{ .Values.azureDevOps.apiUrl | quote }}
  EXPORTER_PORT: {{ .Values.exporter.port | quote }}
  SCRAPE_INTERVAL_SECONDS: {{ .Values.exporter.scrapeIntervalSeconds | quote }}
  LOG_LEVEL: {{ .Values.exporter.logLevel | quote }}
  {{- if .Values.azureDevOps.boardsCustomFields }}
  AZURE_DEVOPS_BOARDS_CUSTOM_FIELDS: {{ .Values.azureDevOps.boardsCustomFields | quote }}
  {{- end }}
  {{- if .Values.azureDevOps.boardsExcludeStates }}
  AZURE_DEVOPS_BOARDS_EXCLUDE_STATES: {{ .Values.azureDevOps.boardsExcludeStates | quote }}
  {{- end }}
