{{- if not .Values.azureDevOps.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-devops-exporter.fullname" . }}
  labels:
    {{- include "azure-devops-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  AZURE_DEVOPS_TOKEN: {{ .Values.azureDevOps.token | quote }}
{{- end }}
